# Generated by Django 4.1.7 on 2023-03-21 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caste_name', models.CharField(max_length=25)),
                ('caste_code', models.CharField(max_length=50, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reli_name', models.CharField(max_length=25)),
                ('reli_code', models.CharField(max_length=50, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('DOB', models.DateField()),
                ('EMailId', models.CharField(max_length=50)),
                ('PhoneNumber', models.IntegerField(default=1)),
                ('caste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IndianMatrimonial.caste')),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IndianMatrimonial.religion')),
            ],
        ),
    ]
